--------------------------------------------------------
--  File created - Tuesday-June-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence AUTHORS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."AUTHORS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 102 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence COMMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."COMMENTS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 77 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NEWS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."NEWS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 95 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TAGS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TEST"."TAGS_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 54 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table AUTHORS
--------------------------------------------------------

  CREATE TABLE "TEST"."AUTHORS" 
   (	"AUTHOR_ID" NUMBER(20,0), 
	"AUTHOR_NAME" NVARCHAR2(30), 
	"EXPIRED" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "TEST"."COMMENTS" 
   (	"COMMENT_ID" NUMBER(20,0), 
	"NEWS_ID" NUMBER(20,0), 
	"COMMENT_TEXT" NVARCHAR2(100), 
	"CREATION_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NEWS
--------------------------------------------------------

  CREATE TABLE "TEST"."NEWS" 
   (	"NEWS_ID" NUMBER(20,0), 
	"TITLE" NVARCHAR2(30), 
	"SHORT_TEXT" NVARCHAR2(100), 
	"FULL_TEXT" NVARCHAR2(2000), 
	"CREATION_DATE" TIMESTAMP (6), 
	"MODIFICATION_DATE" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NEWS_AUTHORS
--------------------------------------------------------

  CREATE TABLE "TEST"."NEWS_AUTHORS" 
   (	"NEWS_ID" NUMBER(20,0), 
	"AUTHOR_ID" NUMBER(20,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NEWS_TAGS
--------------------------------------------------------

  CREATE TABLE "TEST"."NEWS_TAGS" 
   (	"NEWS_ID" NUMBER(20,0), 
	"TAG_ID" NUMBER(20,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE "TEST"."ROLES" 
   (	"ROLE_ID" NUMBER(20,0), 
	"ROLE_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAGS
--------------------------------------------------------

  CREATE TABLE "TEST"."TAGS" 
   (	"TAG_ID" NUMBER(20,0), 
	"TAG_NAME" NVARCHAR2(30)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "TEST"."USERS" 
   (	"USER_ID" NUMBER(20,0), 
	"USER_NAME" NVARCHAR2(50), 
	"LOGIN" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"ROLE_ID" NUMBER(20,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index ROLES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."ROLES_UK1" ON "TEST"."ROLES" ("ROLE_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."USERS_UK1" ON "TEST"."USERS" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TAGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."TAGS_PK" ON "TEST"."TAGS" ("TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."USERS_PK" ON "TEST"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."COMMENTS_PK" ON "TEST"."COMMENTS" ("COMMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NEWS_TAGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."NEWS_TAGS_PK" ON "TEST"."NEWS_TAGS" ("NEWS_ID", "TAG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."ROLES_PK" ON "TEST"."ROLES" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NEWS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."NEWS_PK" ON "TEST"."NEWS" ("NEWS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NEWS_AUTHORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."NEWS_AUTHORS_PK" ON "TEST"."NEWS_AUTHORS" ("NEWS_ID", "AUTHOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AUTHORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEST"."AUTHORS_PK" ON "TEST"."AUTHORS" ("AUTHOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "TEST"."COMMENTS" ADD CONSTRAINT "COMMENTS_PK" PRIMARY KEY ("COMMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."COMMENTS" MODIFY ("COMMENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."COMMENTS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."COMMENTS" MODIFY ("COMMENT_TEXT" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."COMMENTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TEST"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."USERS" MODIFY ("LOGIN" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."USERS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."USERS" ADD CONSTRAINT "USERS_UK1" UNIQUE ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NEWS_TAGS
--------------------------------------------------------

  ALTER TABLE "TEST"."NEWS_TAGS" ADD CONSTRAINT "NEWS_TAGS_PK" PRIMARY KEY ("NEWS_ID", "TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."NEWS_TAGS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."NEWS_TAGS" MODIFY ("TAG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHORS
--------------------------------------------------------

  ALTER TABLE "TEST"."AUTHORS" ADD CONSTRAINT "AUTHORS_PK" PRIMARY KEY ("AUTHOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."AUTHORS" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."AUTHORS" MODIFY ("AUTHOR_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE "TEST"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."ROLES" ADD CONSTRAINT "ROLES_UK1" UNIQUE ("ROLE_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NEWS
--------------------------------------------------------

  ALTER TABLE "TEST"."NEWS" ADD CONSTRAINT "NEWS_PK" PRIMARY KEY ("NEWS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."NEWS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."NEWS" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."NEWS" MODIFY ("SHORT_TEXT" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."NEWS" MODIFY ("FULL_TEXT" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."NEWS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."NEWS" MODIFY ("MODIFICATION_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAGS
--------------------------------------------------------

  ALTER TABLE "TEST"."TAGS" MODIFY ("TAG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."TAGS" MODIFY ("TAG_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."TAGS" ADD CONSTRAINT "TAGS_PK" PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NEWS_AUTHORS
--------------------------------------------------------

  ALTER TABLE "TEST"."NEWS_AUTHORS" ADD CONSTRAINT "NEWS_AUTHORS_PK" PRIMARY KEY ("NEWS_ID", "AUTHOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TEST"."NEWS_AUTHORS" MODIFY ("NEWS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TEST"."NEWS_AUTHORS" MODIFY ("AUTHOR_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "TEST"."COMMENTS" ADD CONSTRAINT "COMMENTS_FK1" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "TEST"."NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NEWS_AUTHORS
--------------------------------------------------------

  ALTER TABLE "TEST"."NEWS_AUTHORS" ADD CONSTRAINT "NEWS_AUTHORS_FK1" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "TEST"."NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "TEST"."NEWS_AUTHORS" ADD CONSTRAINT "NEWS_AUTHORS_FK2" FOREIGN KEY ("AUTHOR_ID")
	  REFERENCES "TEST"."AUTHORS" ("AUTHOR_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NEWS_TAGS
--------------------------------------------------------

  ALTER TABLE "TEST"."NEWS_TAGS" ADD CONSTRAINT "NEWS_TAGS_FK1" FOREIGN KEY ("NEWS_ID")
	  REFERENCES "TEST"."NEWS" ("NEWS_ID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "TEST"."NEWS_TAGS" ADD CONSTRAINT "NEWS_TAGS_FK2" FOREIGN KEY ("TAG_ID")
	  REFERENCES "TEST"."TAGS" ("TAG_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "TEST"."USERS" ADD CONSTRAINT "USERS_FK1" FOREIGN KEY ("LOGIN")
	  REFERENCES "TEST"."ROLES" ("ROLE_NAME") ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTHORS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."AUTHORS_TRG" 
BEFORE INSERT ON AUTHORS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.AUTHOR_ID IS NULL THEN
      SELECT AUTHORS_SEQ.NEXTVAL INTO :NEW.AUTHOR_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEST"."AUTHORS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger COMMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."COMMENTS_TRG" 
BEFORE INSERT ON COMMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COMMENT_ID IS NULL THEN
      SELECT COMMENTS_SEQ.NEXTVAL INTO :NEW.COMMENT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEST"."COMMENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NEWS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."NEWS_TRG" 
BEFORE INSERT ON NEWS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NEWS_ID IS NULL THEN
      SELECT NEWS_SEQ.NEXTVAL INTO :NEW.NEWS_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEST"."NEWS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TAGS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TEST"."TAGS_TRG" 
BEFORE INSERT ON TAGS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TAG_ID IS NULL THEN
      SELECT TAGS_SEQ.NEXTVAL INTO :NEW.TAG_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "TEST"."TAGS_TRG" ENABLE;
